ALTER TABLE users ADD COLUMN IF NOT EXISTS diet_type VARCHAR(50) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS allergies TEXT[] DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS excluded_ingredients TEXT[] DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS cuisine_preferences TEXT[] DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_calorie_goal INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_protein_goal REAL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_fat_goal REAL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_carbs_goal REAL DEFAULT 0;
