version: "3.9"

services:
  app:
    build: .
    container_name: eatnow_app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: always
    volumes:
      - ./images:/app/images
      - ./configs:/app/configs
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=eatnow
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./loki/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
   
  db:
    image: postgres:16
    container_name: eatnow_db
    restart: always
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=eatnow
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
