name: Deploy Backend

on:
  push:
    branches: [ "master" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' 
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56 

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Validate Docker Compose file
        run: docker compose -f docker-compose.yml config

      - name: Run Trivy vulnerability scanner (Code)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          exit-code: '1'
          ignore-unfixed: true

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/timurtuleuov/eatnow:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Логинимся в реестр на сервере
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Переходим к docker-compose
            cd /Projects/eatnow
            
            # Скачиваем ТОЛЬКО новый образ бэкенда
            docker compose pull app
            
            # Пересоздаем ТОЛЬКО контейнер app (остальные не трогаем)
            docker compose up -d --no-deps app

  notify:
    runs-on: ubuntu-latest
    needs: [validate, build-and-push, deploy]
    if: always() 
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Репозиторий: ${{ github.repository }}
            Статус проверок: ${{ needs.validate.result }}
            Статус сборки: ${{ needs.build-and-push.result }}
            Статус деплоя: ${{ needs.deploy.result }}
            Автор: ${{ github.actor }}
            Коммит: ${{ github.event.head_commit.message }}